[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yourapp"              # any name
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]               # packages live under src/
